allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  esbuild: true
  msgpackr-extract: true
  prisma: set this to true or false
  unrs-resolver: true
  workerd: true
